### PR TITLE
Create alex.json

### PR DESCRIPTION
**Pull request by AlexAHK**

### CODE REVIEW

**Comment by rxsharp** [comment]
Your delicious sandwich has been validated and about to get merged!

**Comment by rxsharp** [comment]
You are merged! If you haven't already, please start the repo :) Congratulations on being the first to make a pull request on this repository :+1:

**Comment by AlexAHK** [comment]
Thanks!  You meant "star" the repo, right?

**Comment by rxsharp** [comment]
Yeah! *star lol opps.

**Pull request merged**
